-- ─────────────────────────────────────────────────────────────────────────────
-- SkieZ Fresh Farm — In-App Chat Schema (REUSABLE)
-- Run this in: Supabase Dashboard → SQL Editor → New query
-- ─────────────────────────────────────────────────────────────────────────────

-- ─── 1. Chat Sessions ────────────────────────────────────────────────────────
create table if not exists public.chat_sessions (
    id              uuid         primary key default gen_random_uuid(),
    user_id         uuid         references auth.users(id) on delete set null,
    guest_id        text,
    display_name    text         not null default 'Guest',
    last_message_at timestamptz  default now(),
    admin_unread    int          default 0,
    user_unread     int          default 0,
    created_at      timestamptz  default now()
);

-- ─── 2. Chat Messages ────────────────────────────────────────────────────────
create table if not exists public.chat_messages (
    id          bigint       generated by default as identity primary key,
    session_id  uuid         not null references public.chat_sessions(id) on delete cascade,
    sender_name text         not null default 'Guest',
    is_admin    boolean      not null default false,
    text        text         not null,
    created_at  timestamptz  default now()
);

-- ─── Indexes ──────────────────────────────────────────────────────────────────
create index if not exists idx_chat_sessions_user_id  on public.chat_sessions(user_id);
create index if not exists idx_chat_sessions_guest_id on public.chat_sessions(guest_id);
create index if not exists idx_chat_messages_session  on public.chat_messages(session_id);
create index if not exists idx_chat_messages_created  on public.chat_messages(created_at);

-- ─── Helper RPC Functions (unread counters) ───────────────────────────────────
create or replace function increment_user_unread(session_id uuid)
returns void as $$
    update public.chat_sessions
    set user_unread = user_unread + 1, admin_unread = 0
    where id = session_id;
$$ language sql security definer;

create or replace function increment_admin_unread(session_id uuid)
returns void as $$
    update public.chat_sessions
    set admin_unread = admin_unread + 1, user_unread = 0
    where id = session_id;
$$ language sql security definer;

-- ─── Enable Row Level Security ────────────────────────────────────────────────
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;

-- ─── RLS Policies — cleanup first ─────────────────────────────────────────────
drop policy if exists "chat_sessions_insert" on public.chat_sessions;
drop policy if exists "chat_sessions_select" on public.chat_sessions;
drop policy if exists "chat_sessions_update" on public.chat_sessions;
drop policy if exists "chat_messages_insert" on public.chat_messages;
drop policy if exists "chat_messages_select" on public.chat_messages;

-- ─── RLS Policies — recreate ──────────────────────────────────────────────────
-- Sessions: anyone can create/read/update
create policy "chat_sessions_insert" on public.chat_sessions
    for insert with check (true);

create policy "chat_sessions_select" on public.chat_sessions
    for select using (true);

create policy "chat_sessions_update" on public.chat_sessions
    for update using (true);

-- Messages: anyone can insert/read
create policy "chat_messages_insert" on public.chat_messages
    for insert with check (true);

create policy "chat_messages_select" on public.chat_messages
    for select using (true);
